sudo: required
services:
  - docker

before_install:
  - docker build -t alokrajput13/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alokrajput13/react-test npm test

after_success:
  - docker build -t alokrajput13/multi-client ./client
  - docker build -t alokrajput13/multi-nginx ./nginx
  - docker build -t alokrajput13/multi-server ./server
  - docker build -t alokrajput13/multi-worker ./worker

  #Login to dockerCLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push build images to docker hub
  - docker push alokrajput13/multi-client
  - docker push alokrajput13/multi-nginx
  - docker push alokrajput13/multi-server
  - docker push alokrajput13/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-396355292304
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY